% This function prints table 1 to table1.tex

function [] = printTable1(res, s)
est = res; S = s;
table = ['\\begin{tabular}{r|cccc}\n', ...
    ' & (1) & (2) & (3) & (4) \\\\ \n', ...
    '& OLS & OLS & IV & IV \\\\\\hline \n', ...
    '$\\alpha$ & %4.3f & %4.3f  & %4.3f  & %4.3f \\\\ \n', ...
    '& (%4.3f) & (%4.3f) & (%4.3f) & (%4.3f) \\\\ \n &&&& \\\\ \n', ...
    'FE? & & X & & X \\\\ \n &&&& \\\\ \n', ... 
    '$R^2$ & %3.2f & %3.2f & %3.2f & %3.2f \\\\\n', ...
    'N & %3.0f & %3.0f & %3.0f & %3.0f \\\\\\hline \n', ...
    '\\end{tabular}' ...
    ];

file = fopen('table1.tex', 'w');
fprintf(file, table, ...
    est.ols.b(1),   est.fe.b(1),    est.iv.b(1),    est.iv_fe.b(1), ...
    est.ols.seb(1), est.fe.seb(1),  est.iv.seb(1),  est.iv_fe.seb(1), ...
    est.ols.R2(1),  est.fe.R2(1),   est.iv.R2(1),   est.iv_fe.R2(1), ...
    size(S, 1), size(S, 1), size(S, 1), size(S, 1) ...
    );
fclose(file);

end