% This function prints table 3 to table3.tex

function [] = printTable3(res, names, mergeNames)
mergers = res;
table = ['\\begin{tabular}{r|ccccccccc}\n', ...
    ' & \\multicolumn{4}{c}{Post-Nabisco} &', ...
    ' & \\multicolumn{4}{c}{GM-Quaker} \\\\ \n', ...
    ' & (1) & (2) & (3) & (4) && (1) & (2) & (3) & (4) \\\\\\hline', ...
    '&&&&&&&&&\\\\ \n', ...
    '$\\E{p}$ & %4.3f & %4.3f  & %4.3f  & %4.3f', ...
        '&& %4.3f & %4.3f  & %4.3f  & %4.3f \\\\ \n', ...
    'Med($p$)& %4.3f & %4.3f & %4.3f & %4.3f', ...
        '&& %4.3f & %4.3f  & %4.3f  & %4.3f \\\\ \n', ...
    'Var($p$)& %4.3f & %4.3f & %4.3f & %4.3f', ...
        '&& %4.3f & %4.3f  & %4.3f  & %4.3f \\\\\n &&&&&&&&&\\\\ \n', ...
    '$\\E{s}$ & %4.3f & %4.3f  & %4.3f  & %4.3f', ...
        '&& %4.3f & %4.3f  & %4.3f  & %4.3f \\\\ \n', ...
    'Med($s$)& %4.3f & %4.3f & %4.3f & %4.3f', ...
        '&& %4.3f & %4.3f  & %4.3f  & %4.3f \\\\ \n', ...
    'Var($s$)& %4.3f & %4.3f & %4.3f & %4.3f', ...
        '&& %4.3f & %4.3f  & %4.3f  & %4.3f \\\\\n &&&&&&&&&\\\\ \n', ...
    '\\end{tabular}' ...
    ];

file = fopen('table3.tex', 'w');
fprintf(file, table, ...
    mean(mergers.(mergeNames{1}).(names{1}).p), ...
        mean(mergers.(mergeNames{1}).(names{2}).p), ...
        mean(mergers.(mergeNames{1}).(names{3}).p), ...
        mean(mergers.(mergeNames{1}).(names{4}).p),  ...
    mean(mergers.(mergeNames{2}).(names{1}).p), ...
        mean(mergers.(mergeNames{2}).(names{2}).p), ...
        mean(mergers.(mergeNames{2}).(names{3}).p), ...
        mean(mergers.(mergeNames{2}).(names{4}).p),  ...
    median(mergers.(mergeNames{1}).(names{1}).p), ...
        median(mergers.(mergeNames{1}).(names{2}).p), ...
        median(mergers.(mergeNames{1}).(names{3}).p), ...
        median(mergers.(mergeNames{1}).(names{4}).p),  ...
    median(mergers.(mergeNames{2}).(names{1}).p), ...
        median(mergers.(mergeNames{2}).(names{2}).p), ...
        median(mergers.(mergeNames{2}).(names{3}).p), ...
        median(mergers.(mergeNames{2}).(names{4}).p),  ...
    var(mergers.(mergeNames{1}).(names{1}).p), ...
        var(mergers.(mergeNames{1}).(names{2}).p), ...
        var(mergers.(mergeNames{1}).(names{3}).p), ...
        var(mergers.(mergeNames{1}).(names{4}).p), ...
    var(mergers.(mergeNames{2}).(names{1}).p), ...
        var(mergers.(mergeNames{2}).(names{2}).p), ...
        var(mergers.(mergeNames{2}).(names{3}).p), ...
        var(mergers.(mergeNames{2}).(names{4}).p), ...
    mean(mergers.(mergeNames{1}).(names{1}).s), ...
        mean(mergers.(mergeNames{1}).(names{2}).s), ...
        mean(mergers.(mergeNames{1}).(names{3}).s), ...
        mean(mergers.(mergeNames{1}).(names{4}).s),  ...
    mean(mergers.(mergeNames{2}).(names{1}).s), ...
        mean(mergers.(mergeNames{2}).(names{2}).s), ...
        mean(mergers.(mergeNames{2}).(names{3}).s), ...
        mean(mergers.(mergeNames{2}).(names{4}).s),  ...
    median(mergers.(mergeNames{1}).(names{1}).s), ...
        median(mergers.(mergeNames{1}).(names{2}).s), ...
        median(mergers.(mergeNames{1}).(names{3}).s), ...
        median(mergers.(mergeNames{1}).(names{4}).s),  ...
    median(mergers.(mergeNames{2}).(names{1}).s), ...
        median(mergers.(mergeNames{2}).(names{2}).s), ...
        median(mergers.(mergeNames{2}).(names{3}).s), ...
        median(mergers.(mergeNames{2}).(names{4}).s),  ...
    var(mergers.(mergeNames{1}).(names{1}).s), ...
        var(mergers.(mergeNames{1}).(names{2}).s), ...
        var(mergers.(mergeNames{1}).(names{3}).s), ...
        var(mergers.(mergeNames{1}).(names{4}).s), ...  
    var(mergers.(mergeNames{2}).(names{1}).s), ...
        var(mergers.(mergeNames{2}).(names{2}).s), ...
        var(mergers.(mergeNames{2}).(names{3}).s), ...
        var(mergers.(mergeNames{2}).(names{4}).s) ...    
    );
fclose(file);
end