% This function prints table 4 to table4.tex

function [] = printTable4(res)

vcov = res.vcov; x2 = res.x2; theta1 = res.theta1; se = res.se;
    theta2w = res.theta2w; fval = res.fval; se2w = res.se2w;
    
ymd  = theta1(2:25); xmd  = [x2(1:24,1) x2(1:24,3:4)];
beta = (xmd'*(vcov(2:25,2:25)\xmd))\xmd'*(vcov(2:25,2:25)\ymd);
resmd = ymd - xmd*beta;
semd = sqrt(diag(inv(xmd'*(vcov(2:25,2:25)\xmd))));
mcoef = [beta(1); theta1(1); beta(2:3)];
semcoef = [semd(1); se(1); semd];

Rsq = 1-((resmd-mean(resmd))'*(resmd-mean(resmd)))/((ymd-mean(ymd))'*...
    (ymd-mean(ymd)));
Rsq_G = 1-(resmd'*(vcov(2:25,2:25)\resmd))/((ymd-mean(ymd))'*...
    (vcov(2:25,2:25)\(ymd-mean(ymd))));


table = ['\\begin{tabular}{r|cccccc}\n', ...
    ' & Mean & $\\Sigma$ & Income & Income$^2$ & Age & ' ...
        '$\\one{\\text{Child}}$ \\\\\\hline &&&&&&\\\\ \n', ...
    'Constant   & %4.3f & %4.3f  & %4.3f  & %4.3f & %4.3f & %4.3f', ...
        '\\\\ \n', ...
        ' & (%4.3f) & (%4.3f)  & (%4.3f)  & (%4.3f) & (%4.3f) &', ...
            '(%4.3f) \\\\ \n', ...
    'Price & %4.3f & %4.3f  & %4.3f  & %4.3f & %4.3f & %4.3f \\\\ \n', ...
        ' & (%4.3f) & (%4.3f)  & (%4.3f)  & (%4.3f) & (%4.3f) &', ...
            '(%4.3f) \\\\ \n', ...
    'Sugar & %4.3f & %4.3f  & %4.3f  & %4.3f & %4.3f & %4.3f \\\\ \n', ...
        ' & (%4.3f) & (%4.3f)  & (%4.3f)  & (%4.3f) & (%4.3f) &', ...
            '(%4.3f) \\\\ \n', ...
    'Mushy & %4.3f & %4.3f  & %4.3f  & %4.3f & %4.3f & %4.3f \\\\ \n', ...
        ' & (%4.3f) & (%4.3f)  & (%4.3f)  & (%4.3f) & (%4.3f) &', ...
            '(%4.3f) \\\\ \n', ...
    ' &&&&&& \\\\ \n', ...
    '\\multicolumn{7}{l}{GMM objective: %4.3f} \\\\ \n', ...
    '\\multicolumn{7}{l}{MD $R^2$: %4.3f} \\\\ \n', ...
    '\\multicolumn{7}{l}{MD weighted $R^2$: %4.3f} \\\\\\hline \n', ...
    '\\end{tabular}' ...
    ];

outvec = [];
for i=1:size(theta2w,1)
     outvec = [outvec; mcoef(i); theta2w(i,:)'; semcoef(i); se2w(i,:)'];
end

outvec = [outvec; fval; Rsq; Rsq_G];
file = fopen('table4.tex', 'w');
fprintf(file, table, outvec);

fclose(file);
end